# Generated by Django 6.0.4 on 2026-04-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_groupinvite_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
