# Generated by Django 6.0.4 on 2026-04-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_is_deleted_groupinvite_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
