# Generated by Django 6.0.4 on 2026-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_expense_expensesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('GROCERIES', 'Groceries'), ('RENT', 'Rent'), ('UTILITIES', 'Utilites'), ('INTERNET', 'Internet'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='GROCERIES', max_length=20),
        ),
    ]
