# Generated by Django 6.0.4 on 2026-06-20 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('GROCERIES', 'Groceries'), ('RENT', 'Rent'), ('UTILITIES', 'Utilites'), ('INTERNET', 'Internet'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
