# Generated by Django 6.0.4 on 2026-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_expense_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
