# Generated by Django 6.0.4 on 2026-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_expense_participants_alter_expense_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('PERCENTAGE', 'Percentage'), ('EXACT', 'Exact')], default='EQUAL', max_length=20),
        ),
    ]
