# Generated by Django 6.0.4 on 2026-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_expense_split_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
