# Generated by Django 6.0.4 on 2026-06-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_expensesplit_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='expensesplit',
            name='is_deleted',
        ),
    ]
