# Generated by Django 6.0.4 on 2026-07-27 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_expense_category_ownedamount_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('GROCERIES', 'Groceries'), ('RENT', 'Rent'), ('UTILITIES', 'Utilites'), ('INTERNET', 'Internet'), ('TRANSPORT', 'Transport'), ('OTHER', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownedamount',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
        migrations.AlterField(
            model_name='ownedamount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
