# Generated by Django 6.0.7 on 2026-08-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_groupmember_unique_user_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmember',
            name='unique_user_group',
        ),
    ]
