# Generated by Django 6.0.4 on 2026-09-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_groupmember_unique_user_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnedAmount',
        ),
    ]
