# Generated by Django 6.0.4 on 2026-09-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_ownedamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_by_user', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settled_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
